In [1]:
import numpy as np

$Definir Arrays$

In [2]:
a = np.full((2, 3, 4), 9)

In [3]:
a

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [4]:
np.random.rand(2, 3, 4)    

array([[[0.9022852 , 0.29209986, 0.8987648 , 0.02186828],
        [0.81665435, 0.77646677, 0.34455918, 0.27922036],
        [0.6154927 , 0.57317793, 0.158081  , 0.80306962]],

       [[0.05231172, 0.34709621, 0.0877049 , 0.03498625],
        [0.95805166, 0.97221085, 0.36931808, 0.25563227],
        [0.41322632, 0.50895249, 0.19624741, 0.41849282]]])

In [5]:
b = np.random.rand(2, 3, 4)
b

array([[[0.79893058, 0.99143225, 0.51000899, 0.09161019],
        [0.39678159, 0.30280337, 0.11379812, 0.17484002],
        [0.93129878, 0.62586829, 0.95708131, 0.83939558]],

       [[0.06255221, 0.70124329, 0.92667519, 0.56815559],
        [0.01343604, 0.95028842, 0.69731909, 0.88302296],
        [0.68029626, 0.02893167, 0.30405974, 0.24812609]]])

In [13]:
a, b

(array([[[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]],
 
        [[9, 9, 9, 9],
         [9, 9, 9, 9],
         [9, 9, 9, 9]]]),
 array([[[0.79893058, 0.99143225, 0.51000899, 0.09161019],
         [0.39678159, 0.30280337, 0.11379812, 0.17484002],
         [0.93129878, 0.62586829, 0.95708131, 0.83939558]],
 
        [[0.06255221, 0.70124329, 0.92667519, 0.56815559],
         [0.01343604, 0.95028842, 0.69731909, 0.88302296],
         [0.68029626, 0.02893167, 0.30405974, 0.24812609]]]))


\title{Definición de Funciones}




\title{Definición de Funciones}



## Definición de Funciones

In [14]:
#definición de función
def nombreFuncion(x, y):
    return x + 2 * y
np.fromfunction(nombreFuncion, (3, 5))

array([[ 0.,  2.,  4.,  6.,  8.],
       [ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])


### Array unidemensionales

In [16]:
arrayUni = np.array([1,2,3,4,5,6,7,8,9])
print("Shape:", arrayUni.shape)
print("arrayUni:", arrayUni)

Shape: (9,)
arrayUni: [1 2 3 4 5 6 7 8 9]


In [18]:
#obtener un elemento
arrayUni[3]


4

In [19]:
#obtener los elementos de la posicion 3 a 6
arrayUni[2:5]

array([3, 4, 5])

In [20]:
#obtener elementos segun rango, salto entre elementos
arrayUni[0::2]

array([1, 3, 5, 7, 9])


### Array multidimensional

In [22]:
arrayMulti = np.array([[0,1,2,3,4], [5,6,7,8,9]])
print("Shape: ", arrayMulti.shape)
print('arrayMulti', arrayMulti)

Shape:  (2, 5)
arrayMulti [[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
#accediendo a elementos, cuarto elmento del segundo axis
print('arrayMulti[0,3] = ', arrayMulti[0,3])
print('arrayMulti[1,3] = ', arrayMulti[1,3])

arrayMulti[0,3] =  3
arrayMulti[1,3] =  8


In [26]:
print('todo la fila del primer axis arrayMulti[1, :] = ', arrayMulti[1,:])

todo la fila del primer axis arrayMulti[1, :] =  [5 6 7 8 9]


In [30]:
#accediendo al cuarto elemento del cada segundo axis "arrayM[0(elemento inicial 1axis1):n(elemento final 1axisn), m(elemento del 2axis)]"
print('cuarto elemento de cada segundo axis', arrayMulti[0:2, 3])

cuarto elemento de cada segundo axis [3 8]


In [36]:
#Crear array unidimensional con 28 elementos
array28 = np.arange(28)
print("Shape:", array28.shape)
print("Array:", array28)

Shape: (28,)
Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [37]:
#modificando dimenciones del array
array28.shape = (7,4)
print("Shape:", array28.shape)
print("Array:", array28)

Shape: (7, 4)
Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [42]:
#creardo una copia de referencia al array
array28_cp = array28.reshape(4,7)
print("Shape:", array28_cp.shape)
print("Array:", array28_cp)


Shape: (4, 7)
Array: [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [45]:
array28_cp[0,2] = 50
print("array28_cp[0,2] = ", array28_cp[0,2])

array28_cp[0,2] =  50


In [46]:
#revisar que modifico el array original
print("array28[0,2] = ", array28[0,2])

array28[0,2] =  50


In [48]:
array1 = np.arange(2,20,2)
array2 = np.arange(8)
print("array1 = ", array1)
print("array2 = ", array2)

array1 =  [ 2  4  6  8 10 12 14 16 18]
array2 =  [0 1 2 3 4 5 6 7]
